// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmy17IzxMCX19QZ7DUGOpfxd_1AanMy0I',
    appId: '1:603614216614:web:4e70c0273576931610cf67',
    messagingSenderId: '603614216614',
    projectId: 'chatapptut-b035b',
    authDomain: 'chatapptut-b035b.firebaseapp.com',
    storageBucket: 'chatapptut-b035b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsnH_W5z2jpBPlMNrj55yFsG_iIpdOLfM',
    appId: '1:603614216614:android:4b422200c3795f5a10cf67',
    messagingSenderId: '603614216614',
    projectId: 'chatapptut-b035b',
    storageBucket: 'chatapptut-b035b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD55z0tdP9nb0W5iom8X5ZSUpjOHfsd0o4',
    appId: '1:603614216614:ios:9e9e5a0afb247b4310cf67',
    messagingSenderId: '603614216614',
    projectId: 'chatapptut-b035b',
    storageBucket: 'chatapptut-b035b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD55z0tdP9nb0W5iom8X5ZSUpjOHfsd0o4',
    appId: '1:603614216614:ios:9e9e5a0afb247b4310cf67',
    messagingSenderId: '603614216614',
    projectId: 'chatapptut-b035b',
    storageBucket: 'chatapptut-b035b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmy17IzxMCX19QZ7DUGOpfxd_1AanMy0I',
    appId: '1:603614216614:web:8843516cb7567d4810cf67',
    messagingSenderId: '603614216614',
    projectId: 'chatapptut-b035b',
    authDomain: 'chatapptut-b035b.firebaseapp.com',
    storageBucket: 'chatapptut-b035b.appspot.com',
  );
}
